#include <iostream>

/*Estructura_de_datos_dinámicas_y_no_lineales.
_Un_árbol_consta_de_un_conjunto_finito_de_elementos,_denominados_nodos_y_un_conjunto_finito_de_líneas_dirigidas_denominadas_ramas_,_que_conectan_los_nodos.

ROPIEDADES_DE_LOS_ÁRBOLES

La_longitud_de_camino_es_el_número_de_ramas_que_uno_tiene_que_pasar_hasta_llegar_al_objetivo_y_casi_siempre_se_inicia_desde_el_nodo_raíz_
se_podría_contar_el_número_de_nodos_-1(ese_-1_representa_la_raíz)

¿Cómo_hallamos_la_altura_de_un_nodo_?_Se_tiene_que_ver_desde_las_hojas_hacía_arriba_,_es_decir_si_quisiéramos_saber_la_altura_del_nodo_24_,_
deberíamos_contar_desde_el_nodo_21_,_el_cual_daría_como_resultado_2_,_la_altura_del_24_es_2_por_lo_tanto.


La_profundidad_es_parecido_a_la_altura_,_solo_que_esta_vez_iniciamos_desde_la_raíz_(nivel_0_)_y_luego_vamos_por_sus_ramificaciones
De_este_modo_si_quisiéramos_encontrar_la_profundidad_del_nodo_19_,_veríamos_que_sería_el_Nivel_2


Para_que_un_nodo_sea_hermano_de_otro_nodo_debe_encontrarse_en_el_mismo_nivel_y_ser_hijo_del_mismo_padre_.__En_este_caso_tanto_el_8_como_el_24_son
_hermanoS(_hijos_del_16)_y_el_3_y_el_13_también_(_hijos_del_8_)

El_orden_de_un_árbol_será_la_máxima_cantidad_de_hijos_que_tendrá_cada_nodo. _Si_dijeran_que_un_nodo_tiene_un_orden_2_,_puede_tener
0,_1_o_2_hijos_cómo_máximo*/

using namespace std;

int main(){

    return 0;
}
